<?php
require __DIR__ . '/vendor/autoload.php';

$pdf = new \TCPDF();
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);
$pdf->Write(0, 'Test PDF generated by TCPDF');
$pdf->Output(__DIR__ . '/tmp-valid.pdf', 'F');
